services:
  rclone-browser:
    image: jiatern/rclonebrowser:latest
    restart: unless-stopped
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TZ=Europe/Madrid
      - KEEP_APP_RUNNING=1
      - CLEAN_TMP_DIR=1
    volumes:
      - /mnt/user/appdata/rclonebrowser:/config
      - /mnt/user:/media
    ports:
      - 5800:5800
      - 5900:5900
